AutoTrade.Web/Controllers/CreditCardController.cs
namespace AutoTrade.Web.Controllers
{
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.Authorization;

	using Services.Data.Interfaces;
	using ViewModels.CreditCard;
	using Infrastructure.Extensions;

	using static Common.NotificationMessagesConstants;

    [Authorize]
	public class CreditCardController : Controller
	{
		private readonly ICreditCardService creditCardService;
		private readonly IWalletService walletService;
		private readonly IUserService userService;

		public CreditCardController(ICreditCardService creditCardService, IWalletService walletService, IUserService userService)
		{
			this.creditCardService = creditCardService;
			this.walletService = walletService;
			this.userService = userService;
		}

		[HttpGet]
		public async Task<IActionResult> Add()
		{
			bool hasWallet = await userService.HasWalletByIdAsync(this.User.GetId()!);
			if (!hasWallet)
			{
				TempData[ErrorMessage] = "You do not have a wallet!";

				return RedirectToAction("Index", "Home");
			}

			string? walletId = await walletService.GetIdByUserIdAsync(this.User.GetId()!);
			bool hasCard = await walletService.HasCreditCardByIdAsync(walletId!);
			if (hasCard)
			{
				TempData[ErrorMessage] = "You already have a credit card!";

				return RedirectToAction("Mine", "Wallet");
			}

			CreditCardFormModel fromModel = new CreditCardFormModel();

			return View(fromModel);
		}

		[HttpPost]
		public async Task<IActionResult> Add(CreditCardFormModel formModel)
		{
			bool hasWallet = await userService.HasWalletByIdAsync(this.User.GetId()!);
			if (!hasWallet)
			{
				TempData[ErrorMessage] = "You do not have a wallet!";

				return RedirectToAction("Index", "Home");
			}

			string? walletId = await walletService.GetIdByUserIdAsync(this.User.GetId()!);
			bool hasCard = await walletService.HasCreditCardByIdAsync(walletId!);
			if (hasCard)
			{
				TempData[ErrorMessage] = "You already have a credit card!";

				return RedirectToAction("Mine", "Wallet");
			}

			if (!ModelState.IsValid)
			{
				return View(formModel);
			}

			try
			{
				string creditCardId = await creditCardService.CreateAndReturnIdAsync(formModel, walletId!);
				await walletService.AddCreditCardByIdAndWalletIdAsync(walletId!, creditCardId);

				TempData[SuccessMessage] = "Credit card was added successfully!";
			}
			catch (Exception)
			{
				GeneralError();

				return View(formModel);
			}

			return RedirectToAction("Mine", "Wallet");
		}

		public async Task<IActionResult> Delete(string id)
		{
			bool hasWallet = await userService.HasWalletByIdAsync(this.User.GetId()!);
			if (!hasWallet)
			{
				TempData[ErrorMessage] = "You do not have a wallet!";

				return RedirectToAction("Index", "Home");
			}

			string? walletId = await walletService.GetIdByUserIdAsync(this.User.GetId()!);
			bool hasCard = await walletService.HasCreditCardByIdAsync(walletId!);
			if (!hasCard)
			{
				TempData[ErrorMessage] = "You do not have a credit card!";

				return RedirectToAction("Mine", "Wallet");
			}

			try
			{
				await creditCardService.DeleteByIdAsync(id);
				await walletService.DeleteCreditCardByIdAsync(walletId!);

				TempData[WarningMessage] = "Credit card was successfully deleted!";
			}
			catch (Exception)
			{
				GeneralError();

				return RedirectToAction("Mine", "Wallet");
			}

			return RedirectToAction("Mine", "Wallet");
		}

		[HttpGet]
		public async Task<IActionResult> Withdraw(string id)
		{
			bool cardBelongsToUser = await creditCardService.CardBelongsToUserByIdAsync(id, this.User.GetId()!);
			if (!cardBelongsToUser)
			{
				TempData[ErrorMessage] = "You can only wirhdraw from you card! Please, try with your credit card!";

				return RedirectToAction("Mine", "Wallet");
			}

			WithdrawMoneyFormModel formModel = new WithdrawMoneyFormModel();

			return View();
		}

        [HttpPost]
        public async Task<IActionResult> Withdraw(WithdrawMoneyFormModel formModel, string id)
        {
            bool cardBelongsToUser = await creditCardService.CardBelongsToUserByIdAsync(id, this.User.GetId()!);
            if (!cardBelongsToUser)
            {
                TempData[ErrorMessage] = "You can only wirhdraw from you card! Please, try with your credit card!";

                return RedirectToAction("Mine", "Wallet");
            }

			try
			{
				decimal money = await creditCardService.WithdrawByIdAsync(formModel, id);

				TempData[SuccessMessage] = $"{money.ToString("N"):f2}€ was withdrawn successully to your wallet balance!";
			}
			catch (Exception)
			{
				GeneralError();
            }

			return RedirectToAction("Mine", "Wallet");
        }

        private IActionResult GeneralError()
		{
			TempData[ErrorMessage] =
				"Unexpected error occurred! Please try again later or contact administrator";

			return RedirectToAction("Index", "Home");
		}

	}
}

AutoTrade.Web/Controllers/TransactionController.cs
namespace AutoTrade.Web.Controllers
{
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.Authorization;

	using Services.Data.Interfaces;
	using Infrastructure.Extensions;
	using ViewModels.Transaction;

	using static Common.NotificationMessagesConstants;

	[Authorize]
	public class TransactionController : Controller
	{
		private readonly ISellerService sellerService;
		private readonly ITransactionService transactionService;

		public TransactionController(ISellerService sellerService, ITransactionService transactionService)
		{
			this.sellerService = sellerService;
			this.transactionService = transactionService;
		}

		public async Task<IActionResult> MySoldCars()
		{
			bool sellerExists = await this.sellerService.SellerExistsByUserIdAsync(this.User.GetId()!);
			if (!sellerExists)
			{
				TempData[ErrorMessage] = "You have to be a seller in order to see your sold cars!";

				return RedirectToAction("Become", "Seller");
			}

			List<TransactionSoldAndBoughtCarsViewModel> soldCars = new List<TransactionSoldAndBoughtCarsViewModel>();

			try
			{
				soldCars.AddRange(await this.transactionService.GetSoldCarsByUserIdAsync(this.User.GetId()!));
			}
			catch (Exception)
			{
				GeneralError();
			}

			return View(soldCars);
		}

		public async Task<IActionResult> MyBoughtCars()
		{
			List<TransactionSoldAndBoughtCarsViewModel> boughtCars = new List<TransactionSoldAndBoughtCarsViewModel>();

			try
			{
				boughtCars.AddRange(await transactionService.GetBoughtCarsByUserIdAsync(this.User.GetId()!));
			}
			catch (Exception)
			{
				GeneralError();
			}
			return View(boughtCars);
		}

		private IActionResult GeneralError()
		{
			TempData[ErrorMessage] =
				"Unexpected error occurred! Please try again later or contact administrator";

			return RedirectToAction("Index", "Home");
		}

	}
}

AutoTrade.Web/Views/Shared/_CarFormPartial.cshtml
@model CarFormModel;

<div class="row">
	<div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
		<form method="post">
			<div class="form-group">
				<label asp-for="Make"></label>
				<input asp-for="Make" class="form-control" placeholder="Make...">
				<span asp-validation-for="Make" class="small text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Model"></label>
				<input asp-for="Model" class="form-control"
					   placeholder="Model...">
				<span asp-validation-for="Model" class="small text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Price"></label>
				<input asp-for="Price" class="form-control">
				<span asp-validation-for="Price" class="small text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Year"></label>
				<input asp-for="Year" class="form-control"
					   placeholder="Year...">
				<span asp-validation-for="Year" class="small text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Horsepower"></label>
				<input asp-for="Horsepower" class="form-control"
					   placeholder="Horsepower...">
				<span asp-validation-for="Horsepower" class="small text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Mileage"></label>
				<input asp-for="Mileage" class="form-control"
					   placeholder="Mileage...">
				<span asp-validation-for="Mileage" class="small text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description"></label>
				<textarea asp-for="Description" rows="4" class="form-control"
						  placeholder="The car..."></textarea>
				<span asp-validation-for="Description" class="small text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ImageUrl"></label>
				<input asp-for="ImageUrl" class="form-control"
					   placeholder="Image...">
				<span asp-validation-for="ImageUrl" class="small text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="CategoryId"></label>
				<select asp-for="CategoryId" class="form-control">
					@foreach (var category in Model.Categories)
					{
						<option value="@category.Id">@category.Name</option>
					}
				</select>
				<span asp-validation-for="CategoryId" class="small textdanger"></span>
			</div>
			<div class="form-group">
				<label asp-for="TransmissionId"></label>
				<select asp-for="TransmissionId" class="form-control">
					@foreach (var transmission in Model.Transmissions)
					{
						<option value="@transmission.Id">@transmission.Name</option>
					}
				</select>
				<span asp-validation-for="TransmissionId" class="small textdanger"></span>
			</div>
			<div class="form-group">
				<label asp-for="EngineId"></label>
				<select asp-for="EngineId" class="form-control">
					@foreach (var engineType in Model.EngineTypes)
					{
						<option value="@engineType.Id">@engineType.Type</option>
					}
				</select>
				<span asp-validation-for="EngineId" class="small textdanger"></span>
			</div>
			<div class="text-center">
				<input class="btn btn-primary mt-3" type="submit" value="Save" />
			</div>
		</form>
	</div>
</div>

AutoTrade.Web/Views/Shared/_CarPartial.cshtml
@using AutoTrade.Services.Data.Interfaces;
@using AutoTrade.Web.Infrastructure.Extensions;
@model CarAllViewModel
@inject ICarService CarService
@{
	bool isUserOwnerOfCar = await CarService.IsUserWithIdOwnerOfCarWithIdAsync(Model.Id, this.User.GetId()!);
}


<div class="col-md-4">
	<div class="card mb-3">
		<img class="card-img-top" src="@Model.ImageUrl" alt="Car Image">
		<div class="card-body text-center">
			<h4>@Model.Make @Model.Model</h4>
			<h6>Horsepower: <b>@Model.Horsepower</b></h6>
			<h6>Year: <b>@Model.Year</b></h6>
			<h6>Price: <b>@($"{Model.Price.ToString("N"):f2}") €</b></h6>

			<a asp-area="" asp-controller="Car" asp-action="Details" asp-route-id="@Model.Id"
			   class="btn btn-success">Details</a>

			@if (this.User.Identity?.IsAuthenticated ?? false)
			{
				@if (isUserOwnerOfCar || this.User.IsAdmin())
				{
					<a asp-area="" asp-controller="Car" asp-action="Edit" asp-route-id="@Model.Id"
					   class="btn btn-warning">Edit</a>

					<a asp-area="" asp-controller="Car" asp-action="Delete" asp-route-id="@Model.Id"
					   class="btn btn-danger">Delete</a>

					@if (!Model.IsForSale)
					{
						<form class="input-group-sm" asp-area="" asp-controller="Car"
							  asp-action="ForSale" asp-route-id="@Model.Id" method="post">
							<input class="btn btn-primary" type="submit" value="For Sale" />
						</form>
					}
					else
					{
						<form class="input-group-sm" asp-area="" asp-controller="Car"
							  asp-action="ReturnToGarage" asp-route-id="@Model.Id" method="post">
							<input class="btn btn-primary" type="submit" value="Return to garage" />
						</form>
					}
				}
				if (Model.IsForSale && !isUserOwnerOfCar)
				{
					<form class="input-group-sm" asp-area="" asp-controller="Car"
						  asp-action="Buy" asp-route-id="@Model.Id" method="post">
						<input class="btn btn-primary" type="submit" value="Buy" />
					</form>
				}
			}
		</div>
	</div>
</div>

AutoTrade.Web/Views/Shared/_CreditCardPartial.cshtml
@using AutoTrade.Services.Data.Interfaces;
@using AutoTrade.Web.Infrastructure.Extensions;
@using static AutoTrade.Common.GeneralApplicationConstants;
@model CreditCardViewModel

<div class="col-md-3" style="float:right">
	<img class="card-img-top" src=@creditCardUrl alt="Car Image">
	<div class="card-body text-center">
		<h5>Name on card: @Model.NameOnCard</h5>
		<h6>Card number: <b>@Model.CardNumber</b></h6>
		<h6>Expiration date: <b>@Model.ExpirationDate</b></h6>
		<a asp-controller="CreditCard" asp-action="Delete" asp-route-id="@Model.Id"
		   class="btn btn-danger">Delete</a>
		<a asp-controller="CreditCard" asp-action="Withdraw" asp-route-id="@Model.Id"
		   class="btn btn-success">Withdraw money</a>
	</div>
</div>

AutoTrade.Web/Views/Shared/_Layout.cshtml
@using static AutoTrade.Common.GeneralApplicationConstants;
@using AutoTrade.Services.Data.Interfaces;
@using AutoTrade.Web.Infrastructure.Extensions;

@inject ISellerService SellerService
@{
	bool isUserSeller = await SellerService.SellerExistsByUserIdAsync(this.User.GetId()!);
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - AutoTrade</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/AutoTrade.Web.styles.css" asp-append-version="true" />
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
	<partial name="_NotificationsPartial" />
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoTrade</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="All">All Cars</a>
						</li>
						@if (this.User.Identity?.IsAuthenticated ?? false)
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Mine">My Cars</a>
							</li>

							@if (isUserSeller)
							{
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Add">Add Car</a>
								</li>
							}
						}
					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	 <footer class="border-top footer text-muted">
		<div class="container">
			&copy; AutoTrade @ReleaseYear
			@if (DateTime.UtcNow.Year != ReleaseYear)
			{
				@Html.Raw($" - {DateTime.UtcNow.Year}");
			}
		</div>
	</footer> 
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AutoTrade.Web/Views/Shared/_MyCarsButtons.cshtml
<div class="mt-4 text-center">
	<a asp-area="" asp-controller="Car" asp-action="Mine"
	   class="btn btn-primary btn-lg">Garage</a>
	<a asp-area="" asp-controller="Car" asp-action="CarsForSale"
	   class="btn btn-primary btn-lg">Cars for sale</a>
	<a asp-area="" asp-controller="Transaction" asp-action="MyBoughtCars"
	   class="btn btn-primary btn-lg">Bought cars</a>
	<a asp-area="" asp-controller="Transaction" asp-action="MySoldCars"
	   class="btn btn-primary btn-lg">Sold cars</a>
</div>
<hr />

AutoTrade.Web/Views/Shared/_NotificationsPartial.cshtml
@using static AutoTrade.Common.NotificationMessagesConstants;

@if (TempData.ContainsKey(ErrorMessage))
{
    <script>toastr.error('@TempData[ErrorMessage]');</script>
}

@if (TempData.ContainsKey(WarningMessage))
{
    <script>toastr.warning('@TempData[WarningMessage]');</script>
}

@if (TempData.ContainsKey(InformationMessage))
{
    <script>toastr.info('@TempData[InformationMessage]');</script>
}

@if (TempData.ContainsKey(SuccessMessage))
{
    <script>toastr.success('@TempData[SuccessMessage]');</script>
}